# Generated by Django 5.0.7 on 2024-07-28 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer'},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='profile_pic',
        ),
    ]
