# Generated by Django 5.0.7 on 2024-08-10 12:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(20)])),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(default='', max_length=100, null=True)),
                ('availble', models.BooleanField(default=True)),
                ('catetgory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icecreamShop.category')),
            ],
        ),
    ]
