# Generated by Django 5.0.7 on 2024-08-10 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icecreamShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Products'},
        ),
    ]
