# Generated by Django 5.0.7 on 2024-08-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icecreamShop', '0002_alter_category_options_alter_products_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='product/images'),
        ),
    ]
