# Generated by Django 5.0.7 on 2024-08-18 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icecreamShop', '0004_rename_products_product_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='item_name',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='user_name',
            new_name='user',
        ),
    ]
